const app=document.getElementById('app');
let token=localStorage.getItem('mr_token')||'',user=null,media=[],query='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(url,opt={}){opt.headers=opt.headers||{};if(token)opt.headers.Authorization='Bearer '+token;const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Habaye ikibazo');return d}
function side(id,ico,label){return `<button class="navItem ${location.hash==='#'+id?'active':''}" onclick="page('${id}')"><b>${ico}</b><span>${label}</span></button>`}

function scrollPage(direction){
  const amount=Math.max(300,window.innerHeight*0.78);
  window.scrollBy({top:direction*amount,behavior:'smooth'});
}
function scrollMenu(direction){
  const menu=document.querySelector('.sidebar');
  if(!menu)return;
  const amount=Math.max(180,menu.clientHeight*0.65);
  menu.scrollBy({top:direction*amount,behavior:'smooth'});
}
function nav(){return `<header class="topbar"><button class="brand" onclick="page('home')">RWANDA <em>VIBE</em></button><div class="search"><span>⌕</span><input value="${esc(query)}" placeholder="Shakisha Films, Videos, Music, Gospel, Comedy..." oninput="search(this.value)" onkeydown="if(event.key==='Enter') webSearch(this.value)"><button class="webBtn" onclick="webSearch(document.querySelector('.search input').value)" title="Shakisha kuri Google">Google</button></div><div class="topActions"><div id="google_translate_element" class="langBox"></div>${user?`<button class="pill" onclick="page('profile')">👤 ${esc(user.name)}</button><button class="pill" onclick="logout()">Sohoka</button>`:`<button class="pill primary" onclick="page('login')">🔐 Injira</button>`}</div></header><div class="layout"><aside class="sidebar"><div class="sideScrollBtns"><button onclick="scrollMenu(-1)" title="Zamura menu">▲</button><span>Menu</span><button onclick="scrollMenu(1)" title="Manura menu">▼</button></div><div class="sideNavScroll">${side('home','⌂','Home')}${side('films','🎬','Films')}${side('videos','▶','Videos')}${side('music','♫','Music')}${side('gospel-video','🎤','Gospel Video')}${side('gospel-audio','🎧','Gospel Audio')}${side('comedy','😂','Comedy')}${side('sports','🏆','Siporo & Imyidagaduro')}${side('photos','▧','Photos')}${side('latest','🆕','Latest')}${side('trending','🔥','Trending')}${side('popular','⭐','Popular')}${side('tiktok','📱','Shorts')}${side('live','🔴','Live')}${side('social','●','Social Feed')}${side('chat','💬','Messages')}${side('web','🌐','Google / Web')} ${side('upload','＋','Upload')}<div class="sideSep"></div>${side('profile','☺','Profile')}${user?.role==='admin'?side('admin','⚙','Admin'):''}<div class="guestTip">👀 <b>Reba nta login</b><small>Umuntu wese ashobora kureba content. Login ikenewe kuri Like, Comment, Upload na Live.</small></div></aside><main class="content" id="content"></main></div><div class="scrollControls"><button onclick="scrollPage(-1)" title="Zamura page">▲</button><button onclick="scrollPage(1)" title="Manura page">▼</button></div><nav class="mobileNav">${side('home','⌂','Home')}${side('tiktok','📱','Shorts')}${side('social','●','Social')}${side('live','🔴','Live')}${side(user?'profile':'login',user?'☺':'🔐',user?'Profile':'Injira')}</nav>`}
function scrollMenu(dir){const el=document.querySelector('.sideNavScroll');if(el)el.scrollBy({top:dir*260,behavior:'smooth'});}
function shell(html){app.innerHTML=nav();document.getElementById('content').innerHTML=html+footer();initTranslator()}
function initTranslator(){
 if(window.google?.translate?.TranslateElement)return;
 if(document.getElementById('google-translate-script'))return;
 const s=document.createElement('script');s.id='google-translate-script';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateInit';document.body.appendChild(s);
}
window.googleTranslateInit=function(){new google.translate.TranslateElement({pageLanguage:'rw',includedLanguages:'rw,en,fr,sw,ar,pt,es,de,it,zh-CN,ja,ko,hi,am,ha,yo,zu,tr,ru,nl,pl,sv,no,da,fi,el,th,vi,id,ms,ur,fa',autoDisplay:false},'google_translate_element');}

async function load(type=''){media=await api('/api/media'+(type?'?type='+type:''));return media}
function dateLabel(d){const t=new Date(d);if(Number.isNaN(t.getTime()))return '';const now=new Date(),diff=Math.max(0,now-t),day=86400000;if(diff<day)return 'NSHYA';if(diff<2*day)return 'EJO';if(diff<7*day)return 'IKI CYUMWERU';return t.toLocaleDateString('rw-RW',{day:'2-digit',month:'short',year:'numeric'});}
function dateTime(d){const t=new Date(d);return Number.isNaN(t.getTime())?'':t.toLocaleString('rw-RW',{dateStyle:'medium',timeStyle:'short'});}
function footer(){return `<footer class="siteFooter"><div><b>RWANDA VIBE MEDIA</b><p>Urubuga rw’ibirimo bya siporo, imyidagaduro, Films, Videos, Music, Photos na Social Feed.</p></div><div class="footerLinks"><button onclick="page('about')">About Us</button><button onclick="page('contact')">Contact</button><button onclick="page('privacy')">Privacy Policy</button><button onclick="page('terms')">Terms</button><button onclick="page('copyright')">Copyright</button><button onclick="page('content-policy')">Content Policy</button></div><small>© ${new Date().getFullYear()} MEDIA RWANDA · Content rights belong to their respective owners.</small></footer>`;}
function thumb(x){if(x.poster)return `<img class="thumb" src="/uploads/${esc(x.poster)}" loading="lazy">`;if(x.type==='photo')return `<img class="thumb" src="/uploads/${esc(x.filename)}" loading="lazy">`;if(x.type==='video'||x.type==='film')return `<video class="thumb" src="/uploads/${esc(x.filename)}" muted preload="metadata"></video>`;return `<div class="musicThumb"><span>♫</span><small>MUSIC</small></div>`}
function card(x){return `<article class="card"><div class="thumbWrap" onclick="openMedia(${x.id})">${thumb(x)}<span class="typeBadge">${x.type==='film'?'FILM':x.type.toUpperCase()}</span></div><div class="cardBody"><div class="author">${esc(x.author||'MEDIA RWANDA')} <span class="dateBadge">${dateLabel(x.created_at)}</span></div><h3>${esc(x.title)}</h3><p class="muted">${esc(x.genre||'')} ${x.year?'· '+x.year:''}</p><div class="actions"><button onclick="like(${x.id})">❤️ ${x.likes||0}</button><button onclick="openMedia(${x.id})">💬 ${x.comments||0}</button><button onclick="openMedia(${x.id})">▶ ${x.type==='music'?'Kumva':'Reba'}</button></div></div></article>`}
function section(title,type,items=6){const xs=media.filter(x=>x.type===type).slice(0,items);return `<section><div class="sectionHead"><h2>${title}</h2><button class="linkBtn" onclick="page('${type==='film'?'films':type+'s'}')">Reba byose →</button></div><div class="grid">${xs.map(card).join('')||`<div class="empty">Nta ${type} irimo. Jya kuri Upload wongereho content.</div>`}</div></section>`}
async function home(){query='';await load();const latest=await api('/api/media/section/latest');const trending=await api('/api/media/section/trending');const popular=await api('/api/media/section/popular');shell(`<div class="hero"><div><span class="eyebrow">🇷🇼 RWANDA · ENTERTAINMENT · SOCIAL</span><h1>Reba. Sangiza. Menya.</h1><p>Films, Videos, Music, Photos, Shorts, Live na Social Feed ahantu hamwe. <b>Nta login ikenewe kugira ngo urebe.</b></p><div><button class="bigBtn" onclick="page('latest')">🆕 Reba bishya</button><button class="outlineBtn" onclick="page('tiktok')">📱 Reba Shorts</button></div></div></div><div class="quick"><button onclick="page('latest')">🆕 Latest</button><button onclick="page('trending')">🔥 Trending</button><button onclick="page('popular')">⭐ Popular</button><button onclick="page('films')">🎬 Films</button><button onclick="page('videos')">▶ Videos</button><button onclick="page('music')">♫ Music</button><button onclick="page('photos')">▧ Photos</button><button onclick="page('gospel-video')">🎤 Gospel Video</button><button onclick="page('gospel-audio')">🎧 Gospel Audio</button><button onclick="page('comedy')">😂 Comedy</button><button onclick="page('sports')">🏆 Siporo & Imyidagaduro</button></div><section><div class="sectionHead"><h2>🆕 Bishya</h2><button class="linkBtn" onclick="page('latest')">Reba byose →</button></div><div class="grid">${latest.slice(0,8).map(card).join('')||'<div class="empty">Nta content nshya irimo.</div>'}</div></section><section><div class="sectionHead"><h2>🔥 Trending</h2><button class="linkBtn" onclick="page('trending')">Reba byose →</button></div><div class="grid">${trending.slice(0,8).map(card).join('')||'<div class="empty">Nta trending content irimo.</div>'}</div></section><section><div class="sectionHead"><h2>⭐ Popular</h2><button class="linkBtn" onclick="page('popular')">Reba byose →</button></div><div class="grid">${popular.slice(0,8).map(card).join('')||'<div class="empty">Nta popular content irimo.</div>'}</div></section>${section('🎬 Films zigezweho','film')}${section('▶ Videos zigezweho','video')}${section('▧ Amafoto mashya','photo')}${section('♫ Music','music')}`);location.hash='home'}
async function sportsPage(){
 shell(`<div class="sportsHero"><span class="eyebrow">🏆 RWANDA VIBE MEDIA · SIPORO & IMYIDAGADURO</span><h1>Siporo & Imyidagaduro</h1><p>Amakuru, ibiganiro, videos n’ibikorwa by’imyidagaduro n’imikino. Iyi page ni ahantu hamwe ho gukurikirana ibijyanye na siporo n’imyidagaduro mu Rwanda no hanze.</p></div>
 <section class="sportsGrid">
  <article class="sportsPanel"><div class="sportsIcon">⚽</div><h2>Umupira w’amaguru</h2><p>Kurikirana amakuru, ibiganiro, ibisobanuro by’imikino n’ibindi bitangazwa na MEDIA RWANDA.</p><button class="bigBtn" onclick="page('videos')">Reba Videos →</button></article>
  <article class="sportsPanel"><div class="sportsIcon">🏀</div><h2>Indi siporo</h2><p>Basketball, volleyball, athletics n’indi mikino. Abakoresha bashobora kohereza content yabo biciye kuri Upload.</p><button class="outlineBtn" onclick="page('upload')">Ohereza Content</button></article>
  <article class="sportsPanel"><div class="sportsIcon">🎬</div><h2>Imyidagaduro</h2><p>Films, Comedy, Music, Gospel na Shorts. Reba content nshya kandi ukoreshe search kuyishaka vuba.</p><button class="bigBtn" onclick="page('latest')">Reba ibishya →</button></article>
  <article class="sportsPanel"><div class="sportsIcon">🎤</div><h2>Ibiganiro</h2><p>Interviews, entertainment shows n’ibiganiro by’abahanzi n’abakinnyi. Content yose igomba kubahiriza amategeko y’urubuga.</p><button class="outlineBtn" onclick="page('social')">Social Feed</button></article>
 </section>
 <section class="sportsNote"><h2>📌 Uko wakoresha iyi page</h2><p>Shakisha izina ry’ikipe, umukinnyi, umuhanzi cyangwa programme muri search yo hejuru. Ku content yawe bwite, jya kuri <b>Upload</b> uhitemo category iboneye.</p></section>`);
 location.hash='sports';
}
async function collection(p){const t={films:'film',videos:'video',photos:'photo',music:'music','gospel-video':'video','gospel-audio':'music',comedy:'video'}[p];if(['gospel-video','gospel-audio','comedy'].includes(p))media=await api('/api/media/category/'+p);else await load(t);const titles={films:'🎬 Films',videos:'▶ Videos',photos:'▧ Photos',music:'♫ Music','gospel-video':'🎤 Gospel Video','gospel-audio':'🎧 Gospel Audio',comedy:'😂 Comedy'};shell(`<div class="pageTitle"><div><span class="eyebrow">MEDIA RWANDA</span><h1>${titles[p]}</h1><p class="muted">Reba nta login. Abakoresha bashobora gushyira content kuri page ihuye n'icyiciro bahisemo muri Upload.</p></div><span class="count">${media.length} items</span></div><div class="grid">${media.map(card).join('')||'<div class="empty">Nta content irimo muri iyi page. Jya kuri Upload uhitemo category yayo.</div>'}</div>`);location.hash=p}
async function openMedia(id){const x=await api('/api/media/'+id),comments=await api('/api/media/'+id+'/comments');let player=x.type==='music'?`<audio controls autoplay class="audio" src="/uploads/${esc(x.filename)}"></audio>`:x.type==='photo'?`<img class="detailPhoto" src="/uploads/${esc(x.filename)}">`:`<video controls autoplay class="detailVideo" src="/uploads/${esc(x.filename)}"></video>`;shell(`<button class="backBtn" onclick="page('${x.type==='film'?'films':x.type==='video'?'videos':x.type==='photo'?'photos':'music'}')">← Subira</button><article class="detail"><div class="detailMedia">${player}</div><div class="detailInfo"><span class="typeBadge static">${x.type.toUpperCase()}</span><h1>${esc(x.title)}</h1><p class="muted">By ${esc(x.author||'MEDIA RWANDA')} · ${x.views} views · ${x.year||''}</p><p>${esc(x.description||'')}</p><div class="detailActions"><button class="bigAction" onclick="like(${x.id})">❤️ ${x.likes}</button><button class="bigAction">💬 ${x.comments}</button></div><h2>Comments</h2>${user?`<form class="commentForm" onsubmit="comment(event,${x.id})"><input id="commentText" placeholder="Andika comment..." required><button>Ohereza</button></form>`:'<button class="outlineBtn" onclick="page(\'login\')">🔐 Injira kugira ngo usige comment</button>'}<div>${comments.map(c=>`<div class="commentLine"><b>${esc(c.name)}</b><br>${esc(c.text)}</div>`).join('')||'<p class="muted">Nta comment iraboneka.</p>'}</div></div></article>`);location.hash='media-'+id}
async function like(id){if(!user){alert('Kanda Injira kugira ngo ukunde content. Ushobora kureba nta login.');return}try{await api('/api/media/'+id+'/like',{method:'POST'});openMedia(id)}catch(e){alert(e.message)}}
async function comment(e,id){e.preventDefault();try{await api('/api/media/'+id+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:document.getElementById('commentText').value})});openMedia(id)}catch(err){alert(err.message)}}
function authCard(mode='login'){return `<div class="authCard"><div class="authLogo">MR</div><h1>${mode==='login'?'Murakaza neza 👋':'Fungura konti yawe'}</h1><p class="muted">${mode==='login'?'Injira byoroshye.':'Kora konti mu masegonda make.'}</p>${mode==='login'?`<form onsubmit="doLogin(event)"><input id="email" type="email" autocomplete="email" placeholder="Email" required><input id="pass" type="password" autocomplete="current-password" placeholder="Password" required><button class="bigBtn full">Injira</button></form><p>Nta konti? <button class="textBtn" onclick="page('register')">Iyandikishe</button></p>`:`<form onsubmit="doRegister(event)"><input name="name" autocomplete="name" placeholder="Amazina" required><input name="email" type="email" autocomplete="email" placeholder="Email" required><input name="password" type="password" autocomplete="new-password" minlength="6" placeholder="Password (6+)" required><button class="bigBtn full">Kora konti</button></form><p>Ufite konti? <button class="textBtn" onclick="page('login')">Injira</button></p>`}<button class="guestBtn" onclick="home()">👀 Komeza nka Guest — nta login</button></div>`}
function login(){shell(authCard('login'));location.hash='login'}
function register(){shell(authCard('register'));location.hash='register'}
async function doLogin(e){e.preventDefault();try{const d=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.value,password:pass.value})});token=d.token;user=d.user;localStorage.setItem('mr_token',token);home()}catch(err){alert(err.message)}}
async function doRegister(e){e.preventDefault();try{const d=await api('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});token=d.token;user=d.user;localStorage.setItem('mr_token',token);home()}catch(err){alert(err.message)}}
function logout(){token='';user=null;localStorage.removeItem('mr_token');home()}
function uploadPage(){if(!user)return login();shell(`<div class="formPage"><span class="eyebrow">CREATOR STUDIO</span><h1>＋ Upload Content</h1><p class="muted">Hitamo page/category aho content yawe igomba kugaragara. <b>Uploads z’abakoresha zibanza gusuzumwa na Admin</b> mbere yo gutangazwa.</p><form class="uploadForm" onsubmit="doUpload(event)"><input name="title" placeholder="Title / Izina rya content" required><textarea name="description" placeholder="Description"></textarea><select name="type" id="uploadType" onchange="syncUploadCategory()"><option value="film">🎬 Film</option><option value="video">▶ Video</option><option value="music">♫ Music</option><option value="photo">▧ Photo</option></select><select name="category" id="uploadCategory"><option value="normal">General</option><option value="gospel-video">🎤 Gospel Video</option><option value="gospel-audio">🎧 Gospel Audio</option><option value="comedy">😂 Comedy</option></select><div class="two"><input name="genre" placeholder="Genre"><input name="year" type="number" placeholder="Year"></div><label class="fileBox">📁 Hitamo file<input name="file" type="file" required></label><label class="fileBox">🖼️ Poster / Cover (optional)<input name="poster" type="file" accept="image/*"></label><label class="checkLine"><input type="checkbox" name="rights_confirm" required> Ndemeza ko mfite uburenganzira bwo gutangaza iyi content kandi ko itarimo content itemewe.</label><button class="bigBtn">Ohereza kuri review</button></form></div>`);location.hash='upload'}
function syncUploadCategory(){const t=document.getElementById('uploadType'),c=document.getElementById('uploadCategory');if(!t||!c)return;for(const o of c.options){o.disabled=(o.value==='gospel-video'&&t.value!=='video')||(o.value==='gospel-audio'&&t.value!=='music')||(o.value==='comedy'&&t.value!=='video');}if(c.options[c.selectedIndex]?.disabled)c.value='normal';}

async function doUpload(e){e.preventDefault();try{await api('/api/media',{method:'POST',body:new FormData(e.target)});alert('Upload yakozwe neza 🎉');home()}catch(err){alert(err.message)}}
async function social(){const posts=await api('/api/feed');shell(`<div class="pageTitle"><div><span class="eyebrow">FACEBOOK-STYLE</span><h1>● Social Feed</h1><p class="muted">Sangiza abantu ibyo ukunda.</p></div>${user?'<button class="bigBtn" onclick="newPost()">＋ Post</button>':''}</div><div class="feed">${posts.map(postCard).join('')||'<div class="empty">Nta post irimo. Ba uwa mbere!</div>'}</div>`);location.hash='social'}
function postCard(p){let m=p.media_filename?(p.media_type==='photo'?`<img class="postMedia" src="/uploads/${esc(p.media_filename)}">`:`<video class="postMedia" src="/uploads/${esc(p.media_filename)}" controls></video>`):'';return `<article class="post"><div class="postHead"><div class="avatar">${esc((p.author||'M')[0].toUpperCase())}</div><div><b>${esc(p.author)}</b><small> · ${new Date(p.created_at).toLocaleString()}</small></div></div><p>${esc(p.text)}</p>${m}<div class="postActions"><button onclick="postLike(${p.id})">❤️ ${p.likes}</button><button onclick="postComments(${p.id})">💬 ${p.comments}</button><button onclick="navigator.clipboard?.writeText(location.origin+'/#social');alert('Link yandukuwe')">↗ Sangiza</button></div></article>`}
async function newPost(){if(!user)return login();shell(`<div class="formPage small"><h1>＋ Kora Post</h1><form class="uploadForm" onsubmit="doPost(event)"><textarea name="text" placeholder="Ni iki ushaka gusangiza abantu?" rows="5"></textarea><label class="fileBox">📷 Shyiraho Photo/Video (optional)<input name="file" type="file" accept="image/*,video/*"></label><button class="bigBtn">Publish Post</button></form></div>`);location.hash='new-post'}
async function doPost(e){e.preventDefault();try{await api('/api/feed',{method:'POST',body:new FormData(e.target)});social()}catch(err){alert(err.message)}}
async function postLike(id){if(!user)return login();await api('/api/feed/'+id+'/like',{method:'POST'});social()}
async function postComments(id){const c=await api('/api/feed/'+id+'/comments');const txt=c.length?c.map(x=>x.name+': '+x.text).join('\n\n'):'Nta comments kuri iyi post.';prompt('Comments (read-only):',txt)}

let activeChatId=null, activeChatUserId=null, chatPollTimer=null;
function stopChatPolling(){if(chatPollTimer){clearInterval(chatPollTimer);chatPollTimer=null;}}
function chatAvatar(u){return u?.avatar?`<img src="/uploads/${esc(u.avatar)}" alt="">`:`<span>${esc((u?.name||'U')[0].toUpperCase())}</span>`}
async function chatPage(selectId=null){
  if(!user)return login();
  stopChatPolling();
  activeChatId=selectId||activeChatId;
  const [chats,people]=await Promise.all([api('/api/chats'),api('/api/chat/users')]);
  shell(`<div class="chatPage">
    <section class="chatSidebar">
      <div class="chatTop"><div><span class="eyebrow">PRIVATE CHAT</span><h1>💬 Messages</h1></div></div>
      <input class="chatSearch" placeholder="Shakisha umuntu..." oninput="searchChatPeople(this.value)">
      <div id="chatPeople"></div>
      <div class="chatListTitle">Chats zawe</div>
      <div id="chatList">${chatListHtml(chats)}</div>
    </section>
    <section class="chatWindow" id="chatWindow">${activeChatId?'<div class="empty">Gutegereza...</div>':'<div class="chatWelcome"><div class="chatWelcomeIcon">💬</div><h2>Tangira ikiganiro</h2><p>Hitamo umuntu ibumoso wandikirane na we.</p></div>'}</section>
  </div>`);
  renderChatPeople(people);
  document.querySelector('.chatPage')?.classList.toggle('hasChat',!!activeChatId);
  location.hash='chat';
  if(activeChatId) await openChat(activeChatId);
}
function chatListHtml(chats){
  if(!chats.length)return '<div class="chatEmpty">Nta kiganiro uratangira.</div>';
  return chats.map(c=>`<button class="chatItem ${Number(c.id)===Number(activeChatId)?'selected':''}" onclick="openChat(${c.id})">
    <div class="chatAvatar">${chatAvatar({name:c.other_name,avatar:c.other_avatar})}</div>
    <div class="chatItemBody"><b>${esc(c.other_name)}</b><small>${esc(c.last_text||'Nta butumwa')}${c.unread?` · <strong>${c.unread} nshya</strong>`:''}</small></div>
  </button>`).join('');
}
function renderChatPeople(people){
  const el=document.getElementById('chatPeople'); if(!el)return;
  el.innerHTML=people.length?people.map(p=>`<button class="chatPerson" onclick="startChat(${p.id})"><div class="chatAvatar">${chatAvatar(p)}</div><div><b>${esc(p.name)}</b><small>${esc(p.email)}</small></div></button>`).join(''):'<div class="chatEmpty">Nta muntu abonetse.</div>';
}
let chatPeopleTimer=null;
async function searchChatPeople(q){
  clearTimeout(chatPeopleTimer);
  chatPeopleTimer=setTimeout(async()=>{try{renderChatPeople(await api('/api/chat/users?q='+encodeURIComponent(q)))}catch{}},250);
}
async function startChat(userId){
  activeChatUserId=Number(userId);
  // The backend creates the chat only when the first message is sent.
  const people=await api('/api/chat/users');
  const person=people.find(x=>Number(x.id)===activeChatUserId);
  const win=document.getElementById('chatWindow');
  if(win)win.innerHTML=chatComposer(person||{id:userId,name:'Umukoresha'});
  document.querySelectorAll('.chatPerson,.chatItem').forEach(x=>x.classList.remove('selected'));
  setTimeout(()=>document.querySelector('#chatInput')?.focus(),50);
}
async function openChat(chatId){
  activeChatId=Number(chatId);
  const chats=await api('/api/chats'); const c=chats.find(x=>Number(x.id)===activeChatId);
  if(!c)return chatPage();
  activeChatUserId=Number(c.other_id);
  const win=document.getElementById('chatWindow'); if(!win)return chatPage(activeChatId);
  document.querySelector('.chatPage')?.classList.add('hasChat');
  win.innerHTML=chatComposer({id:c.other_id,name:c.other_name,avatar:c.other_avatar},c);
  await refreshMessages();
  stopChatPolling();
  chatPollTimer=setInterval(refreshMessages,2500);
  document.querySelectorAll('.chatItem').forEach(x=>x.classList.remove('selected'));
  const selected=[...document.querySelectorAll('.chatItem')].find(x=>x.getAttribute('onclick')?.includes(String(chatId))); selected?.classList.add('selected');
}
function chatComposer(person,c){
  return `<div class="chatHeader"><div class="chatAvatar">${chatAvatar(person)}</div><div><b>${esc(person.name)}</b><small>Private message</small></div></div>
    <div class="messages" id="messages"><div class="empty">Loading...</div></div>
    <form class="chatComposer" onsubmit="sendChat(event)"><input id="chatInput" maxlength="5000" autocomplete="off" placeholder="Andika ubutumwa..." required><button title="Ohereza">➤</button></form>`;
}
async function refreshMessages(){
  if(!activeChatId)return;
  try{
    const rows=await api('/api/chats/'+activeChatId+'/messages');
    const box=document.getElementById('messages'); if(!box)return;
    const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<120;
    box.innerHTML=rows.map(m=>`<div class="bubbleRow ${Number(m.sender_id)===Number(user.id)?'mine':'theirs'}"><div class="bubble"><span>${esc(m.text).replace(/\n/g,'<br>')}</span><small>${new Date(m.created_at).toLocaleTimeString('rw-RW',{hour:'2-digit',minute:'2-digit'})}${Number(m.sender_id)===Number(user.id)?(m.read_at?' ✓✓':' ✓'):''}</small></div></div>`).join('')||'<div class="empty">Nta butumwa. Tangira wandike.</div>';
    if(nearBottom)box.scrollTop=box.scrollHeight;
  }catch(err){console.warn(err)}
}
async function sendChat(e){
  e.preventDefault(); const input=document.getElementById('chatInput'); const text=input?.value.trim(); if(!text||!activeChatUserId)return;
  const btn=e.target.querySelector('button'); if(btn)btn.disabled=true;
  try{
    await api('/api/chats/'+activeChatUserId+'/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});
    input.value='';
    const chats=await api('/api/chats'); const c=chats.find(x=>Number(x.other_id)===Number(activeChatUserId));
    if(c){activeChatId=Number(c.id);await refreshMessages()}
    if(btn)btn.disabled=false;
  }catch(err){if(btn)btn.disabled=false;alert(err.message)}
}
async function live(){const rooms=await api('/api/live');shell(`<div class="pageTitle"><div><span class="eyebrow">LIVE</span><h1>🔴 Live Rwanda</h1><p class="muted">Reba live rooms nta login. Host ashobora gushyiramo stream link.</p></div>${user?'<button class="bigBtn" onclick="newLive()">＋ Tangiza Live</button>':''}</div><div class="liveGrid">${rooms.map(l=>`<article class="liveCard"><div class="liveScreen">${l.status==='live'?'🔴 LIVE':'📅'}<span>${esc(l.status)}</span></div><div class="cardBody"><h2>${esc(l.title)}</h2><p class="muted">Hosted by ${esc(l.host)}</p><p>${esc(l.description||'')}</p>${l.stream_url?`<a class="bigBtn" href="${esc(l.stream_url)}" target="_blank" rel="noopener">▶ Fungura Live</a>`:`<span class="muted">Stream link iracyategurwa.</span>`}</div></article>`).join('')||'<div class="empty">Nta Live room irimo.</div>'}</div>`);location.hash='live'}
function newLive(){if(!user)return login();shell(`<div class="formPage small"><h1>🔴 Tangiza Live</h1><p class="muted">Shyiramo link ya stream niba ukoresha streaming service.</p><form class="uploadForm" onsubmit="doLive(event)"><input name="title" placeholder="Live title" required><textarea name="description" placeholder="Description"></textarea><input name="stream_url" type="url" placeholder="Stream URL (optional)"><select name="status"><option value="live">🔴 Live ubu</option><option value="scheduled">📅 Scheduled</option></select><button class="bigBtn">Tangaza Live</button></form></div>`);location.hash='new-live'}
async function doLive(e){e.preventDefault();try{await api('/api/live',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});live()}catch(err){alert(err.message)}}
async function tiktok(){await load();const xs=media.filter(x=>['video','film'].includes(x.type));shell(`<div class="shortsHead"><span class="eyebrow">TIKTOK-STYLE</span><h1>📱 Shorts</h1><p class="muted">Vertical feed. Scroll down urebe video ikurikira. Nta login ikenewe.</p></div><div class="shorts">${xs.map(x=>`<article class="short"><div class="shortVideo">${x.type==='film'?`<video src="/uploads/${esc(x.filename)}" controls playsinline preload="metadata"></video>`:`<video src="/uploads/${esc(x.filename)}" controls playsinline preload="metadata"></video>`}</div><div class="shortInfo"><b>${esc(x.title)}</b><span>${esc(x.author||'MEDIA RWANDA')}</span><small>👁 ${x.views||0} · ❤️ ${x.likes||0}</small><button class="bigBtn" onclick="openMedia(${x.id})">Reba details</button></div></article>`).join('')||'<div class="empty">Nta Shorts irimo. Upload video kugira ngo itangire kugaragara hano.</div>'}</div>`);location.hash='tiktok'}
async function curated(kind,title,subtitle){const xs=await api('/api/media/section/'+kind);shell(`<div class="pageTitle"><div><span class="eyebrow">MEDIA RWANDA</span><h1>${title}</h1><p class="muted">${subtitle}</p></div><span class="count">${xs.length} items</span></div><div class="grid">${xs.map(card).join('')||'<div class="empty">Nta content ihari.</div>'}</div>`);location.hash=kind}
function infoPage(kind){const pages={about:['About Us','Rwanda Vibe Media ni urubuga rwo gusangiza no kureba Films, Videos, Music, Photos, Sports, Entertainment, Shorts na Social Feed.'],contact:['Contact','Ku bibazo bya site, copyright, content report cyangwa ubufatanye, koresha uburyo bwa contact bwashyizweho n’umuyobozi wa site cyangwa report iri kuri content bireba.'],privacy:['Privacy Policy','Turakusanya amakuru akenewe mu gukora konti, login, uploads, comments na security. Browser ishobora gukoresha local storage cyangwa cookies zikenewe ku login no ku mikorere ya site. Ntidusaba amakuru bwite arenze ibikenewe mu gukoresha serivisi.'],terms:['Terms & Conditions','Ukoresha Rwanda Vibe Media wemera kubahiriza amategeko, copyright, privacy n’amabwiriza ya platform. Ukoresha Upload uremeza ko ufite uburenganzira bwo gutangaza file wohereje.'],copyright:['Copyright / DMCA','Niba uri nyir’uburenganzira kuri content iri kuri Rwanda Vibe Media kandi ukeka ko yakoreshejwe nta burenganzira, tanga report irimo URL/content, ibisobanuro by’uburenganzira n’uburyo bwo kukugeraho.'], 'content-policy':['Community & Content Policy','Birabujijwe kohereza content y’abandi nta burenganzira, spam, scams, malware, deceptive content cyangwa content ibujijwe n’amategeko. User uploads zibanza kujya kuri pending kugira ngo Admin azisuzume.']};const [title,text]=pages[kind]||pages.about;shell(`<article class="legalPage"><span class="eyebrow">MEDIA RWANDA</span><h1>${title}</h1><p>${text}</p><h2>Content n’amakuru</h2><p>Buri content igira igihe yashyizweho n’igihe yavuguruwe. Content nshya igaragara muri Latest, naho iya kera ishobora kujya muri Archive.</p><h2>Kwamamaza</h2><p>Kwamamaza bikorwa gusa ku pages no mu buryo bwubahiriza amabwiriza y’abatanga advertising. Nta fake buttons, forced clicks cyangwa redirects bigamije kwamamaza byemewe.</p></article>`);location.hash=kind}
function profile(){if(!user)return login();shell(`<div class="profileCard"><div class="avatar big">${esc((user.name||'M')[0].toUpperCase())}</div><h1>${esc(user.name)}</h1><p>${esc(user.email)}</p><span class="role">${esc(user.role)}</span><p class="muted">${esc(user.bio||'MEDIA RWANDA member')}</p><button class="outlineBtn" onclick="logout()">Sohoka</button></div>`);location.hash='profile'}
async function adminPage(){
 if(!user||user.role!=='admin')return login();
 try{
  const [s,us,ms,reports]=await Promise.all([
    api('/api/admin/stats'),api('/api/admin/users'),api('/api/admin/media'),api('/api/admin/reports')
  ]);
  const pending=ms.filter(x=>x.status==='pending');
  const published=ms.filter(x=>x.status==='published');
  const rejected=ms.filter(x=>x.status==='rejected');
  const mediaRows=(rows,empty)=>rows.map(x=>`<div class="adminRow">
    <div><b>${esc(x.title)}</b><small>${x.type} · ${esc(x.author||'Unknown')} · ${x.views||0} views · ❤️ ${x.likes||0} · 💬 ${x.comments||0} · ${dateTime(x.created_at)}</small></div>
    <select onchange="setMediaStatus(${x.id},this.value)"><option value="published" ${x.status==='published'?'selected':''}>Published</option><option value="pending" ${x.status==='pending'?'selected':''}>Pending</option><option value="rejected" ${x.status==='rejected'?'selected':''}>Rejected</option></select>
    <button onclick="previewAdminMedia(${x.id})">▶</button><button onclick="editMedia(${x.id})">✏️</button><button class="danger" onclick="delMedia(${x.id})">🗑️</button>
  </div>`).join('')||`<p class="muted">${empty}</p>`;
  shell(`<div class="pageTitle"><div><span class="eyebrow">ADMIN CONTROL CENTER</span><h1>⚙ Admin Dashboard</h1><p class="muted">Hano ni ho ucunga users, uploads, approvals, reports n'umutekano wa Rwanda Vibe Media.</p></div><button class="outlineBtn" onclick="adminPage()">↻ Refresh</button></div>
  <div class="stats adminStats">${[['Users',s.users,'👥'],['Media',s.media,'🎬'],['Posts',s.posts,'📝'],['Comments',s.comments,'💬'],['Views',s.views,'👁'],['Live',s.live,'🔴'],['Pending',s.pending||pending.length,'⏳'],['Reports',s.open_reports||0,'🚨']].map(a=>`<div><span class="statIcon">${a[2]}</span><b>${a[1]}</b><span>${a[0]}</span></div>`).join('')}</div>
  <div class="adminGrid">
   <section class="adminPanel priority"><div class="panelHead"><div><h2>⏳ Content isaba review</h2><p class="muted">Uploads nshya ntizigaragara ku rubanda kugeza Admin azemeje.</p></div><span class="adminBadge ${pending.length?'warning':''}">${pending.length} Pending</span></div>${mediaRows(pending,'Nta content iri waiting review.')}</section>
   <section class="adminPanel"><div class="panelHead"><div><h2>🚨 Reports</h2><p class="muted">Reba kandi ucunge reports za media na Social Feed.</p></div><span class="adminBadge ${reports.some(r=>r.status==='open')?'warning':''}">${reports.filter(r=>r.status==='open').length} Open</span></div>${reports.map(r=>`<div class="adminRow reportRow"><div><b>${esc(r.media_title||('Social Post #'+r.post_id)||'Content itazwi')}</b><small>👤 ${esc(r.reporter||'Unknown')} · ${esc(r.reason)} · ${dateTime(r.created_at)} · <strong>${esc(r.status||'open')}</strong></small></div><div class="adminActions">${r.media_id?`<button onclick="openMedia(${r.media_id})">👁 Reba</button>`:''}<button onclick="setReportStatus(${r.id},'resolved')">✅ Resolve</button><button onclick="setReportStatus(${r.id},'dismissed')">↩ Dismiss</button></div></div>`).join('')||'<p class="muted">Nta report iriho.</p>'}</section>
   <section class="adminPanel"><h2>🔐 Hindura Admin Password</h2><form onsubmit="changeAdminPassword(event)" class="adminForm"><input id="adminCurrent" type="password" placeholder="Password iriho" required><input id="adminNext" type="password" placeholder="Password nshya (8+)" minlength="8" required><input id="adminNext2" type="password" placeholder="Subiramo password nshya" minlength="8" required><button class="bigBtn">Bika Password</button></form></section>
   <section class="adminPanel"><div class="panelHead"><div><h2>👥 Abakoresha</h2><p class="muted">Role, uploads, posts, status no gusiba konti.</p></div><span class="adminBadge">${us.length}</span></div><div class="adminToolbar"><input id="adminUserSearch" placeholder="Shakisha user..." oninput="filterAdminRows('adminUsers',this.value)"></div><div id="adminUsers">${us.map(x=>`<div class="adminRow filterRow"><div><b>${esc(x.name)} ${x.disabled?'🚫':''}</b><small>${esc(x.email)} · ${x.role} · ${x.uploads||0} uploads · ${x.posts||0} posts · ${dateTime(x.created_at)}</small></div><select onchange="setUserRole(${x.id},this.value)"><option value="user" ${x.role==='user'?'selected':''}>user</option><option value="admin" ${x.role==='admin'?'selected':''}>admin</option></select><button onclick="setUserDisabled(${x.id},${!x.disabled})">${x.disabled?'▶ Enable':'⏸ Disable'}</button><button class="danger" onclick="deleteUser(${x.id})">🗑️</button></div>`).join('')||'<p class="muted">Nta users.</p>'}</div></section>
   <section class="adminPanel full"><div class="panelHead"><div><h2>🎬 Media Management</h2><p class="muted">${published.length} published · ${pending.length} pending · ${rejected.length} rejected</p></div><span class="adminBadge">${ms.length}</span></div><div class="adminToolbar"><input id="adminMediaSearch" placeholder="Shakisha media..." oninput="filterAdminRows('adminMedia',this.value)"><select onchange="filterAdminMediaStatus(this.value)"><option value="all">Status zose</option><option value="pending">Pending</option><option value="published">Published</option><option value="rejected">Rejected</option></select></div><div id="adminMedia">${ms.map(x=>`<div class="adminRow filterRow mediaAdminRow" data-status="${x.status}"><div><b>${esc(x.title)}</b><small>${x.type} · ${esc(x.author||'Unknown')} · ${x.views||0} views · ❤️ ${x.likes||0} · ${x.status}</small></div><select onchange="setMediaStatus(${x.id},this.value)"><option value="published" ${x.status==='published'?'selected':''}>Published</option><option value="pending" ${x.status==='pending'?'selected':''}>Pending</option><option value="rejected" ${x.status==='rejected'?'selected':''}>Rejected</option></select><button onclick="previewAdminMedia(${x.id})">▶</button><button onclick="editMedia(${x.id})">✏️</button><button class="danger" onclick="delMedia(${x.id})">🗑️</button></div>`).join('')||'<p class="muted">Nta media.</p>'}</div></section>
  </div>`);
  location.hash='admin';
 }catch(e){alert(e.message)}
}
function filterAdminRows(id,q){const root=document.getElementById(id);if(!root)return;const needle=String(q||'').toLowerCase().trim();root.querySelectorAll('.filterRow').forEach(r=>{r.style.display=!needle||r.textContent.toLowerCase().includes(needle)?'flex':'none'})}
function filterAdminMediaStatus(status){document.querySelectorAll('#adminMedia .mediaAdminRow').forEach(r=>{r.style.display=status==='all'||r.dataset.status===status?'flex':'none'})}
async function previewAdminMedia(id){try{const x=await api('/api/admin/media');const m=x.find(a=>Number(a.id)===Number(id));if(!m)return;const src='/uploads/'+encodeURIComponent(m.filename);const body=m.type==='music'?`<audio class="adminPreviewMedia" src="${src}" controls></audio>`:m.type==='photo'?`<img class="adminPreviewMedia" src="${src}" alt="">`:`<video class="adminPreviewMedia" src="${src}" controls playsinline></video>`;shell(`<div class="detail"><div class="detailMedia">${body}</div><div class="detailInfo"><button class="backBtn" onclick="adminPage()">← Subira kuri Admin</button><h1>${esc(m.title)}</h1><p class="muted">${esc(m.description||'')} · Status: ${esc(m.status)}</p></div></div>`);location.hash='admin-preview'}catch(e){alert(e.message)}}
async function changeAdminPassword(e){e.preventDefault();const next=document.getElementById('adminNext').value,next2=document.getElementById('adminNext2').value;if(next!==next2)return alert('Password nshya zombi ntizihura.');try{await api('/api/admin/password',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({current:document.getElementById('adminCurrent').value,next})});alert('Password ya admin yahinduwe neza.');e.target.reset()}catch(e){alert(e.message)}}
async function setUserRole(id,role){try{await api('/api/admin/users/'+id+'/role',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});adminPage()}catch(e){alert(e.message)}}
async function setUserDisabled(id,disabled){if(!confirm(disabled?'Hagarika uyu mukoresha?':'Subizaho uyu mukoresha?'))return;try{await api('/api/admin/users/'+id+'/disabled',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({disabled})});adminPage()}catch(e){alert(e.message)}}
async function setReportStatus(id,status){try{await api('/api/admin/reports/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});adminPage()}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('Siba uyu mukoresha n’ibikorwa bye? Ibi ntibisubizwa inyuma.'))return;try{await api('/api/admin/users/'+id,{method:'DELETE'});adminPage()}catch(e){alert(e.message)}}
async function setMediaStatus(id,status){try{await api('/api/admin/media/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});adminPage()}catch(e){alert(e.message)}}
async function editMedia(id){const all=await api('/api/admin/media');const x=all.find(m=>Number(m.id)===Number(id));if(!x)return;const title=prompt('Title:',x.title);if(title===null)return;const description=prompt('Description:',x.description||'');const genre=prompt('Genre:',x.genre||'');const year=prompt('Year:',x.year||'');const fd=new FormData();fd.append('title',title);fd.append('description',description||'');fd.append('type',x.type);fd.append('genre',genre||'');fd.append('year',year||'');try{await api('/api/media/'+id,{method:'PUT',body:fd});adminPage()}catch(e){alert(e.message)}}
async function delMedia(id){if(!confirm('Siba iyi content burundu? Ibi ntibisubizwa inyuma.'))return;try{await api('/api/media/'+id,{method:'DELETE'});adminPage()}catch(e){alert(e.message)}}

let searchTimer;async function search(q){query=q;clearTimeout(searchTimer);if(!q.trim()){if(location.hash==='#home'||!location.hash)home();return}searchTimer=setTimeout(async()=>{try{const x=await api('/api/search?q='+encodeURIComponent(q));shell(`<div class="pageTitle"><div><span class="eyebrow">SEARCH</span><h1>🔎 Ibisubizo</h1></div><span class="count">${x.length}</span></div><div class="grid">${x.map(card).join('')||'<div class="empty">Nta cyo twabonye.</div>'}</div>`)}catch(e){alert(e.message)}},250)}

function webSearch(q){const term=String(q||'').trim();if(!term){page('web');return}page('web');setTimeout(()=>{const f=document.getElementById('googleFrame');if(f)f.src='https://www.google.com/search?q='+encodeURIComponent(term)},0)}
function web(){shell(`<div class="webSearchPage"><div class="webLogo"><b>G</b> MEDIA RWANDA <span>WEB HUB</span></div><h1>Internet ahantu hamwe</h1><p class="muted">Shakisha Google, cyangwa ufungure YouTube, TikTok, Facebook na Instagram muri MEDIA RWANDA.</p><form class="googleForm" onsubmit="event.preventDefault();webSearch(document.getElementById('webQuery').value)"><input id="webQuery" autofocus placeholder="Shakisha kuri Google..." value="${esc(query)}"><button>🔎 Shakisha</button></form><div class="webQuick"><button onclick="webSearch(document.getElementById('webQuery').value)">🌐 Google</button><button onclick="openHub('https://www.youtube.com/results?search_query='+encodeURIComponent(document.getElementById('webQuery').value),'YouTube')">▶ YouTube</button><button onclick="openHub('https://www.tiktok.com/search?q='+encodeURIComponent(document.getElementById('webQuery').value),'TikTok')">📱 TikTok</button><button onclick="openHub('https://www.facebook.com/search/top?q='+encodeURIComponent(document.getElementById('webQuery').value),'Facebook')">📘 Facebook</button><button onclick="openHub('https://www.instagram.com/explore/search/keyword/?q='+encodeURIComponent(document.getElementById('webQuery').value),'Instagram')">📸 Instagram</button></div><div class="hubFrameWrap"><iframe id="googleFrame" title="Google Search" referrerpolicy="no-referrer-when-downgrade"></iframe><div id="hubMsg" class="webNote">Andika icyo ushaka hejuru. Google ishobora kwanga kwerekanwa muri iframe kubera umutekano wayo; icyo gihe dukenera Google Programmable Search Engine (CX) kugira ngo ibisubizo bigume imbere muri MEDIA RWANDA.</div></div></div>`);location.hash='web'}
function openHub(url,name){shell(`<div class="webSearchPage"><div class="webLogo">${name} <span>MEDIA RWANDA HUB</span></div><p class="muted">${name} ntireka buri gihe ko pages zayo zishyirwa muri iframe. Iyo ibujije embed, koresha button yo kuyifungura hanze.</p><div class="hubFrameWrap"><iframe src="${url}" title="${name}" allowfullscreen></iframe></div><button class="bigBtn" onclick="window.open('${url.replace(/'/g,"\\'")}','_blank','noopener,noreferrer')">Fungura ${name}</button></div>`);location.hash='web'}
function googleType(type){const q=String(document.getElementById('webQuery')?.value||query).trim();if(!q)return web();const urls={images:'https://www.google.com/search?tbm=isch&q=',news:'https://www.google.com/search?tbm=nws&q=',videos:'https://www.google.com/search?tbm=vid&q='};window.open((urls[type]||urls.images)+encodeURIComponent(q),'_blank','noopener,noreferrer')}
function googleMaps(){const q=String(document.getElementById('webQuery')?.value||query).trim();if(!q)return web();window.open('https://www.google.com/maps/search/'+encodeURIComponent(q),'_blank','noopener,noreferrer')}
function page(p){if(p==='home')return home();if(p==='web')return web();if(p==='login')return login();if(p==='register')return register();if(p==='upload')return uploadPage();if(p==='social')return social();if(p==='chat')return chatPage();if(p==='live')return live();if(p==='tiktok')return tiktok();if(['films','videos','photos','music','gospel-video','gospel-audio','comedy'].includes(p))return collection(p);if(p==='sports')return sportsPage();if(['latest','trending','popular','old'].includes(p))return curated(p,p==='latest'?'🆕 Latest':p==='trending'?'🔥 Trending':p==='popular'?'⭐ Popular':'📦 Archive','Ibi byatoranyijwe hakurikijwe itariki, views, likes na comments.');if(['about','contact','privacy','terms','copyright','content-policy'].includes(p))return infoPage(p);if(p==='profile')return profile();if(p==='admin')return adminPage()}
(async()=>{if(token)try{user=await api('/api/me')}catch{token='';localStorage.removeItem('mr_token')}home()})();
